# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  #default: info #too much
  logs:
    pyscript: info #NOGO #use log.warning("var {var}") #with logger.set_level() in set_ef:
    pyscript.file.set_ef.set_ef: info #NOGO? see set_ef #logger.set_level(**{"pyscript.file.set_ef.set_ef": "info"})
    #custom_components.solarman.solarman: error #NOGO? see set_ef #logger.set_level() too

pyscript:
  allow_all_imports: true
  hass_is_global: true

input_number:
  inv_out_manual:
    name: inv_out_manual
    min: 0
    max: 800
    step: 10
    unit_of_measurement: "W"
  discharge_limit:
    name: Discharge Limit
    min: 30
    max: 70
    step: 5
    unit_of_measurement: "%"
    icon: mdi:battery-charging-100
    initial: 70

input_boolean:
  automate:
    name: Automate
  ran_today:
    name: ran_today
    initial: False
  morning:
    name: morning
    initial: False
  override_em:
    name: override_em

sensor:
  - platform: template
    sensors:
      sunrise_next_time:
        friendly_name: "Sunrise next"
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') }}"
      sunset_next_time:
        friendly_name: "Sunset next"
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M') }}"

input_button:
  shutdown_button:
    name: Shutdown HA
    icon: mdi:power
