# for version of 20240913 1200 and later
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    homeassistant.helpers: error
    homeassistant.util.loop: error #blocking loop (solarman)
    homeassistant.components.mqtt.client: error
    homeassistant.components.pyscript: warning
    custom_components.pyscript: warning
    custom_components.solarman: error
    custom_components.solarman.sensor: error

pyscript:
  allow_all_imports: true
  hass_is_global: true

input_number:
  inv_out_manual:
    name: inv_out_manual
    min: 0
    max: 800
    step: 10
    unit_of_measurement: "W"
  battery_charge:
    name: battery_charge
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:battery-charging-100
    initial: 0
  discharge_limit:
    name: Discharge Limit
    min: 30
    max: 70
    step: 5
    unit_of_measurement: "%"
    icon: mdi:battery-charging-100
    initial: 35
  solar_1_watts:
    name: solar_1_watts
    min: 0
    max: 500
    unit_of_measurement: "W"
    initial: 0.0
    mode: box
  solar_2_watts:
    name: solar_2_watts
    min: 0
    max: 500
    unit_of_measurement: "W"
    initial: 0.0
    mode: box
  solar_1_in_power:
    name: delta_solar_1
    min: 0
    max: 1000
    unit_of_measurement: "W"
    initial: 0.0
    mode: box
  solar_2_in_power:
    name: delta_solar_2
    min: 0
    max: 1000
    unit_of_measurement: "W"
    initial: 0.0
    mode: box
  total_in_power:
    name: delta_total_in_power
    min: 0
    max: 4000
    unit_of_measurement: "W"
    initial: 0
    mode: box
  input_int:
    initial: 2
    min: 0
    max: 100
    step: 1
    mode: box

input_boolean:
  automate:
    name: Automate
  ran_today:
    name: ran_today
    initial: False
  morning:
    name: morning
    initial: True
  override_em:
    name: override_em
    initial: False
  ef_loop:
    initial: True

sensor:
  - platform: template
    sensors:
      sunrise_next_time:
        friendly_name: "Sunrise next"
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') }}"
      sunset_next_time:
        friendly_name: "Sunset next"
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M') }}"

input_button:
  shutdown_button:
    name: Shutdown HA
    icon: mdi:power
