# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
ecoflow_key: "<access_key>"
ecoflow_secret: "<secret_key>"
ps_snr: "HW51..." #PowerStream serial number
delta_snr: "R351..." #Delta (2 Max) serial number
shrdzm_snr: "" #smart meter
